### ISSUE TITLE
Support for io.js

### ISSUE THREAD

**Issue by eventEmitter** [jhs67/picha#6]
Hi

Are you planning to add support for the node.js fork [io.js](https://github.com/iojs/io.js)?

**Comment by jhs67** [comment]
Yes, I am planning to support io.js, but I haven't started yet.

**Comment by eventEmitter** [comment]
yeah! thanks!

**Comment by jhs67** [comment]
I ported over to nan and everything seems to be working with io.js, so I published 0.4.5.

**Comment by eventEmitter** [comment]
thanks a lot!
