### ISSUE TITLE
Fantastic

### ISSUE THREAD

**Issue by abuchanan** [jhs67/picha#8]
I first found node-png. That seems extremely outdated at this point and I couldn't get it to compile or work, same for many others. I swear I have searched and searched for a good image encoding library. I didn't find one so I started writing my own wrapper for libpng. Somehow, through that, I stumbled on this library and it is perfect and pretty much exactly what I was about to write.

I wouldn't normally do this, but I had to open an issue to tell you thanks. This needed to be done.

The only issue really is that it's hard to find in the long list of (sometimes junk) image packages)

Thanks mate!

**Comment by jhs67** [comment]
Thanks for the kind words. Is there maybe a keyword or something else you could suggest to make the
package more discoverable?

**Comment by abuchanan** [comment]
Nah, looks like you've got all the keywords I would think. The problem is it's buried in a long list of other image packages.  Not sure how you overcome that.
